/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import javax.swing.JScrollPane;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import System.Employee.Earning;
import System.Employee.PayPeriod;
import System.Employee.AttendanceRecord;
import System.Employee.Benefit;
import System.Employee.Deduction;
import System.Employee.EmployeeRecords;
import java.awt.BorderLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Default
 */
public class EmployeePayroll extends javax.swing.JFrame {
private DefaultTableModel model;
private EmployeeRecords[] employees;
private AttendanceRecord[] attendance;
    /**
     * Creates new form EmployeePayroll
     */
    public EmployeePayroll() throws ParseException {
    
        initComponents();
        // Load employee records from CSV when the form is initialized
        String csvFileName = "src/Files/EmployeeData.csv";
        employees = EmployeeRecords.readEmployeesFromCSV(csvFileName);
        attendance = AttendanceRecord.readAttendanceFromCSV("src/Files/Attendance.csv");
        PanelMonthlyPayrollReport.setVisible(false);
        RunPayrollTable.setVisible(true);
        displayCSVData(csvFileName); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelRunPayroll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RunPayrollTable = new javax.swing.JTable();
        PanelMonthlyPayrollReport = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RunPayrollTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("Employee List");

        jButton1.setText("Monthly Payroll Report");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Run Payroll");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PanelRunPayroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        RunPayrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Status", "Position", "Net Pay"
            }
        ));
        jScrollPane1.setViewportView(RunPayrollTable);

        javax.swing.GroupLayout PanelRunPayrollLayout = new javax.swing.GroupLayout(PanelRunPayroll);
        PanelRunPayroll.setLayout(PanelRunPayrollLayout);
        PanelRunPayrollLayout.setHorizontalGroup(
            PanelRunPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRunPayrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelRunPayrollLayout.setVerticalGroup(
            PanelRunPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRunPayrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelMonthlyPayrollReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        RunPayrollTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee #", "Full Name", "Department", "Gross Income", "SSS No.", "SSS Contribution", "Philhealth No.", "Philhealth Contribution  ", "Pag-ibig No.  ", "Pag-Ibig Contribution  ", "TIN", "Withholding  Tax  ", "Net Pay  "
            }
        ));
        RunPayrollTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(RunPayrollTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMonthlyPayrollReportLayout = new javax.swing.GroupLayout(PanelMonthlyPayrollReport);
        PanelMonthlyPayrollReport.setLayout(PanelMonthlyPayrollReportLayout);
        PanelMonthlyPayrollReportLayout.setHorizontalGroup(
            PanelMonthlyPayrollReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMonthlyPayrollReportLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelMonthlyPayrollReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PanelMonthlyPayrollReportLayout.setVerticalGroup(
            PanelMonthlyPayrollReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMonthlyPayrollReportLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelRunPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelMonthlyPayrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(592, 592, 592))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelRunPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelMonthlyPayrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


      PanelMonthlyPayrollReport.setVisible(false);
      PanelRunPayroll.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PanelMonthlyPayrollReport.setVisible(true);
      PanelRunPayroll.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String selectedMonth = (String) jComboBox1.getSelectedItem();
    Deduction deduction = new Deduction();
    DefaultTableModel model = (DefaultTableModel) RunPayrollTable1.getModel();
    model.setRowCount(0);
    
    //Iterate over each column
        for (int columnIndex = 0; columnIndex < RunPayrollTable.getColumnCount(); columnIndex++) {
            TableColumn column = RunPayrollTable.getColumnModel().getColumn(columnIndex);
            int preferredWidth = 0;
            
            // Iterate over each row in the column to find the maximum preferred width
            for (int rowIndex = 0; rowIndex < RunPayrollTable.getRowCount(); rowIndex++) {
                TableCellRenderer cellRenderer = RunPayrollTable.getCellRenderer(rowIndex, columnIndex);
                Component cellComponent = RunPayrollTable.prepareRenderer(cellRenderer, rowIndex, columnIndex);
                preferredWidth = Math.max(preferredWidth, cellComponent.getPreferredSize().width);
            }
            
        }
            
        RunPayrollTable1.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 14));
        RunPayrollTable1.setFont(new Font("SansSerif", Font.PLAIN, 12));
        RunPayrollTable1.setRowHeight(25);
        
    
        model.setColumnIdentifiers(new String[]{"Employee #", "Full Name", "Position", "Gross Income", "SSS No","SSS Contributon",
            "Philheath No","Philheath Contribtion", "Pag-ibig No", "Pag-ibig Contribution", "Tin No", "Withholdong","NetPay"
               });
        
        for (EmployeeRecords employee : employees)
     if (selectedMonth.equals("September")) {
         String csvfile = "src/Files/EmployeeData.csv";
         try (BufferedReader br = new BufferedReader(new FileReader(csvfile))) {
             String line;
           
            //Skip the first line (header)
            br.readLine();
            while ((line = br.readLine()) != null) {
                String[] data = line.split(";");
                String fullName = data[1] + " " + data [2];
                
                double grossSalary = employee.getGrossSalary();
                double totalDeduction = deduction.totalDeduction(employee);
                double takehomepay = grossSalary - totalDeduction;
             
               model.addRow(new Object[]{data[0], fullName ,data[11], "Php" + " " +grossSalary*2 ,employee.getSss(),"Php" + " " +deduction.calculateSssContribution(employee)
                       ,employee.getPhilHealth(), "Php" + " " +deduction.calculatePhilhealthContribution(employee),employee.getPagIbig(),"Php" + " " + deduction.calculatePagibigContribution(employee),employee.getTin(),"Php" + " " +deduction.calculateTax(employee) , "Php" + " " +takehomepay});
            }
            
            break;
            
        } catch (IOException e) {
            e.printStackTrace();
        }
      // Set custom cell renderer for all columns
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < RunPayrollTable1.getColumnCount(); i++) {
            RunPayrollTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
         
     }
   
   
 
   
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    
    
    
     private void displayCSVData(String csvFile) throws ParseException {
         
        DefaultTableModel model = (DefaultTableModel) RunPayrollTable.getModel();
        model.setRowCount(0);
      
        // Iterate over each column
        for (int columnIndex = 0; columnIndex < RunPayrollTable.getColumnCount(); columnIndex++) {
            TableColumn column = RunPayrollTable.getColumnModel().getColumn(columnIndex);
            int preferredWidth = 0;
            
            // Iterate over each row in the column to find the maximum preferred width
            for (int rowIndex = 0; rowIndex < RunPayrollTable.getRowCount(); rowIndex++) {
                TableCellRenderer cellRenderer = RunPayrollTable.getCellRenderer(rowIndex, columnIndex);
                Component cellComponent = RunPayrollTable.prepareRenderer(cellRenderer, rowIndex, columnIndex);
                preferredWidth = Math.max(preferredWidth, cellComponent.getPreferredSize().width);
            }
            
            // Set the preferred width for the column
            column.setPreferredWidth(preferredWidth + RunPayrollTable.getIntercellSpacing().width);
        }
        //Customize header
        RunPayrollTable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 14));
        RunPayrollTable.setFont(new Font("SansSerif", Font.PLAIN, 12));
        RunPayrollTable.setRowHeight(25);
        
       
        Deduction deduction = new Deduction();
        
        
        model.setColumnIdentifiers(new String[]{"Employee #", "Last Name", "First Name", "Status", "Position","NetPay"
               });
       
        for (EmployeeRecords employee : employees)
        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
             String line;
           
            //Skip the first line (header)
            br.readLine();
            while ((line = br.readLine()) != null) {
                String[] data = line.split(";");
                
                double grossSalary = employee.getGrossSalary();
                double totalDeduction = deduction.totalDeduction(employee);
                double takehomepay = grossSalary - totalDeduction;
             
               model.addRow(new Object[]{data[0], data[1], data[2], data[10],data[11], "Php" + " " + takehomepay});
            }
            
             break;
             
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Center align cells
       
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < RunPayrollTable.getColumnCount(); i++) {
            RunPayrollTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
      // Determine which panel to add the table to based on the visibility of PanelRunPayroll
     if (PanelRunPayroll.isVisible()) {
        // PanelRunPayroll is currently visible, so the table is already added to it
    } else {
        // PanelMonthlyPayrollReport is currently visible, so the table is already added to it
    }

        // Enable row selection
        RunPayrollTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    }
     
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeePayroll().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(EmployeePayroll.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMonthlyPayrollReport;
    private javax.swing.JPanel PanelRunPayroll;
    private javax.swing.JTable RunPayrollTable;
    private javax.swing.JTable RunPayrollTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
